export const ADD_INVALID_CRED = "ADD_INVALID_CRED";
export const REMOVE_INVALID_CRED = "REMOVE_INVALID_CRED";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_CURRENT_USER_SHOPPING_LIST = "GET_CURRENT_USER_SHOPPHING_LIST";
export const GET_ITEMS_IN_EACH_SHOPPING_LIST =
  "GET_ITEMS_IN_EACH_SHOPPING_LIST";
export const SET_ITEM_DETAILS = "SET_ITEM_DETAILS";
export const SAVE_ITEM_URL = "SAVE_ITEM_URL";
export const CLEAR_ITEM_DETAILS = "CLEAR_ITEM_DETAILS";
export const PRE_SELECTED_LIST = "PRE_SELECTED_LIST";
export const CLEAR_PRE_SELECTED_LIST = "CLEAR_PRE_SELECTED_LIST";
export const ADD_LIST = "ADD_LIST";
export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
export const REMOVE_CURRENT_USER = "REMOVE_CURRENT_USER";
