export const ADD_INVALID_CRED = "ADD_INVALID_CRED";
export const REMOVE_INVALID_CRED = "REMOVE_INVALID_CRED";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_USER_SHOPPING_LIST = "SET_USER_SHOPPHING_LIST";
export const ADD_LIST = "ADD_LIST";
